#!/bin/bash

# Vite-build-script: ”vite-build-script” wich
# belongs to the ”mish/browser/” directory

# Production directory is ”../server/”
prodcat="../server/public/"
messcat="../server/"

# Produce a build stamp message, check this before ”git push”:
# If --watch [true] is active, the lines below don't process until
# the script is restarted after being stopped manually with ^C
echo "Producing Mish build timestamp ..."
clock=`date +%y%m%d-%H%M`
echo 'Build '$clock
mestxt='build '$clock
hint=' · for modern browsers only · '
echo $mestxt$hint > ${messcat}buildstamp.txt
echo "...done. Remember rebuild before git push!"
date;

pnpm vite build --mode='production' --emptyOutDir --outDir=$prodcat --watch
