#!/bin/bash
# Script ”deploy-mish” for SCP copy of Mish files to a server
# Also copying scripts as project backup

pwd=$PWD

# The 'a' server list should be carefully adapted:
#test server at home lan    at remote server lan      remote server on internet
a=("tore@192.168.0.116:" "minneadmin@192.168.1.108:" "minneadmin@mish.hopto.org:")
a=("tore@mynta:" "minneadmin@192.168.1.108:" "minneadmin@mish.hopto.org:")
echo
echo "Choose a target server:"
PS3="Enter a number: "
COLUMNS=1
select dest in "${a[@]}"; do
  copyto=$dest
  break
done

if [[ $copyto == "" ]]; then
  echo "Cancelled"
  cd $pwd
  exit
fi

echo
echo 'Should Mish be deployed to the server place'
echo -n "  $copyto? (y/N): "
read yN
if [[ $yN != 'y' && $yN != 'yes' ]]; then
  echo "Nothing copied"
  cd $pwd
  exit
fi

# Project files to be copied to the web root of the server
tocopy='app/ public/ _imdb_news.txt _imdb_settings.sqlite _imdb_similarity buildstamp.txt ld_imdb.js .htaccess LICENSE.txt nodestamp.txt package.json robots.txt server.js'
echo
echo "To copy:"
for x in $tocopy; do
  echo " $x"
done
echo
echo -n 'Confirm (y/N): '
read yN
if [[ $yN != 'y' && $yN != 'yes' ]]; then
  echo "Ended with nothing copied"
  cd $pwd
  exit
fi
echo
echo "Copying all files to the web root:"
# The Mish project server directory:
cd ~/Arbeten/mish/server
scp -r $tocopy $copyto"/var/www/mish"
if [[ $? == 0 ]]; then
  echo "Ended with no error"
else
  echo "Ended with error code $?"
fi
echo

# Script files used in the project's javascript code:
required='finddupimages finderrimg pentaxdebug set_xmp_description xmp_description xmpset finddupnames mkpng set_xmp_creator xmp_creator xmpget'
# Utility scripts, useful for Mish administration from command line:
service=' deploy-mish exif_dimension grind ran4add rm-mini-show set_xmp_creatordate exif_dateorig findlinks ls-kill-ssh ls-pnpm ls-nvm ls-ssd ls-temp ran4mk.js rm-mini-show-symlinks'

# The source directory of required and service Mish scripts:
cd /usr/local/bin
echo "Copying scripts to "$copyto
scp $required$service $copyto"~/usr.local.bin"
if [[ $? == 0 ]]; then
  echo "Ended with no error"
else
  echo "Ended with error code $?"
fi
echo
echo "Next, on "$copyto" Move the files in ~/usr.local.bin to /usr/local/bin!"
echo
# Copy the scripts also to the project to be later saved by git, must be carefully adapted:
cp $required /home/tore/Arbeten/mish/.usr.local.bin
cp $service /home/tore/Arbeten/mish/.mish.service.scripts
echo "Scripts also saved in the Mish project"
echo "NOTE: this 'deploy-mish' script has to be"
echo "much modified for use on another computer!"

cd $pwd
echo
