#!/bin/bash

# Use: grind -r "what" / grep-find
pwd=$PWD
prd=/home/tore/Arbeten/mish # Project directory
if [[ ! $# = 2 ]]; then
  echo 'Use two grep parameters, typically ´grind -r something´'
  echo '(the second may contain regular expressions)'
  exit 1;
fi
cd $prd # (Git) project directory
grep -n --color --exclude='.*' --exclude='*lock*' --exclude-dir='*public*' --exclude-dir='tmp' --exclude-dir='dist' --exclude-dir='.git*' --exclude-dir='*node_modules*' $1 "$2"
cd $pwd
