#!/bin/bash
#ls-pnpm
echo "Useful command to clean up and reinstall from package.json:" > /tmp/tmp
echo "rm -rf node_modules pnpm-lock.yaml tmp dist && pnpm store prune && pnpm i" >> /tmp/tmp
echo >> /tmp/tmp
pnpm help -a >> /tmp/tmp
less /tmp/tmp
